import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'proj-forensics-2023-x',
    title: 'Cyber Forensics Semester Project — X Sem (2023 Batch)',
    abstract: 'A forensic investigation framework to recover artifacts from disk images and analyze the timeline of attacker activities with visual reports.',
    description: 'Full forensic pipeline including disk imaging, file carving, timeline analysis, and visual reports. Built with Python, Sleuthkit, and custom parsers. Includes automated reporting for classroom grading. The toolkit supports ext4 and NTFS file systems with cross-platform capability.',
    year: '2023',
    batch: 'X Sem (2023)',
    categories: ['Cyber Forensics'],
    tags: ['forensics', 'timeline', 'disk', 'sleuthkit', 'python'],
    links: [
      { label: 'GitHub', url: 'https://github.com/example/forensics-project', type: 'github' },
      { label: 'Report PDF', url: 'https://example.com/forensics-report.pdf', type: 'paper' }
    ],
    featured: true,
    imageUrl: '/demo/forensics.svg',
    contributors: ['A. Singh', 'R. Kumar', 'P. Thapa'],
  },
  {
    id: 'proj-vapt-vi-2024',
    title: 'VAPT Web Application Assessment — VI Sem (2024 Batch)',
    abstract: 'End-to-end vulnerability assessment and penetration testing on a mock web application with a full remediation checklist and executive report.',
    description: 'Comprehensive VAPT engagement on a deliberately vulnerable web application (DVWA). Covers discovery, exploitation, and post-exploitation reporting. Tools used: Nmap, Nikto, Burp Suite, SQLMap. Final deliverable includes a CVSS-scored vulnerability report with severity rankings.',
    year: '2024',
    batch: 'VI Sem (2024)',
    categories: ['VAPT'],
    tags: ['vapt', 'web', 'burpsuite', 'sqlmap', 'reporting'],
    links: [
      { label: 'GitHub', url: 'https://github.com/example/vapt-project', type: 'github' },
      { label: 'Live Demo', url: 'https://demo.example.com', type: 'demo' }
    ],
    featured: true,
    imageUrl: '/demo/vapt.svg',
    contributors: ['S. Regmi', 'M. Adhikari'],
  },
  {
    id: 'proj-network-analysis-2022',
    title: 'Network Traffic Anomaly Visualizer (2022)',
    abstract: 'Visual analytics toolkit for PCAP files to detect anomalies and flag common attack patterns with interactive dashboards.',
    description: 'A web app that accepts PCAP uploads and generates statistical charts, protocol breakdowns, and signature-based flags for quick triage. Uses PyShark on the backend and React with Recharts on the frontend. Detects port scans, ARP poisoning, and DNS tunneling.',
    year: '2022',
    batch: 'VIII Sem (2022)',
    categories: ['Network Security'],
    tags: ['pcap', 'visualization', 'pyshark', 'anomaly-detection'],
    links: [
      { label: 'GitHub', url: 'https://github.com/example/pcap-visualizer', type: 'github' }
    ],
    featured: false,
    imageUrl: '/demo/pcap.svg',
    contributors: ['M. Sharma', 'B. Rai'],
  },
  {
    id: 'proj-malware-analysis-2023',
    title: 'Lightweight Malware Sandbox Toolkit (2023)',
    abstract: 'A lightweight sandbox to execute suspected binaries in an instrumented environment and extract behavioral indicators of compromise.',
    description: 'Runs unknown binaries inside a Docker-based isolated environment with system call tracing via strace and network capture. YARA rules engine integrated for IOC extraction. Generates a structured JSON report with process tree, file system changes, and network connections.',
    year: '2023',
    categories: ['Malware Analysis', 'Research'],
    tags: ['sandbox', 'yara', 'docker', 'strace', 'ioc'],
    links: [
      { label: 'Research Paper', url: 'https://example.com/malware-paper.pdf', type: 'paper' }
    ],
    featured: true,
    imageUrl: '/demo/malware.svg',
    contributors: ['L. Rao', 'C. Tamang'],
  },
  {
    id: 'proj-iot-security-2021',
    title: 'Campus IoT Security Audit (2021)',
    abstract: 'An audit of common IoT devices deployed on campus with a mitigation playbook for secure configuration and network segmentation.',
    year: '2021',
    categories: ['IoT'],
    tags: ['iot', 'audit', 'firmware', 'zigbee'],
    links: [],
    featured: false,
    imageUrl: '/demo/iot.svg',
    contributors: ['Team IoT'],
  },
  {
    id: 'proj-memory-forensics-2024',
    title: 'Memory Forensics Automation Toolkit (2024)',
    abstract: 'Automated volatile memory capture and analysis toolkit for extracting process artifacts, injected code, and network connections.',
    description: 'Scripts and wrappers around Volatility3 to automate artifact collection from live and captured memory images. Includes automated plugin chaining, timeline reconstruction, and HTML report generation. Supports Windows and Linux memory profiles.',
    year: '2024',
    categories: ['Cyber Forensics'],
    tags: ['memory', 'forensics', 'volatility', 'artifacts'],
    links: [
      { label: 'GitHub', url: 'https://github.com/example/memory-forensics', type: 'github' }
    ],
    featured: false,
    imageUrl: '/demo/forensics.svg',
    contributors: ['N. Koirala', 'A. Limbu'],
  },
  {
    id: 'proj-vapt-mobile-2023',
    title: 'Android Mobile VAPT Framework (2023)',
    abstract: 'Vulnerability assessment focused on Android app misconfigurations, insecure storage, and API security flaws.',
    year: '2023',
    categories: ['VAPT'],
    tags: ['mobile', 'android', 'vapt', 'frida', 'adb'],
    links: [],
    featured: false,
    imageUrl: '/demo/vapt.svg',
    contributors: ['R. Adhikari'],
  },
  {
    id: 'proj-threat-hunting-2022',
    title: 'Threat Hunting Playbook & Sigma Rules (2022)',
    abstract: 'A documented threat-hunting playbook with Sigma rules and KQL queries for detecting common attacker TTPs across SIEM platforms.',
    year: '2022',
    categories: ['Threat Hunting', 'Research'],
    tags: ['sigma', 'hunt', 'siem', 'kql', 'mitre'],
    links: [
      { label: 'Playbook PDF', url: 'https://example.com/threat-playbook.pdf', type: 'docs' }
    ],
    featured: false,
    imageUrl: '/demo/pcap.svg',
    contributors: ['S. Joshi', 'D. Rana'],
  },
  {
    id: 'proj-cloud-security-2024',
    title: 'CIS Cloud Security Baseline Automator (2024)',
    abstract: 'CIS Benchmark-based automation to validate AWS and GCP accounts, score posture, and generate prioritized remediation tasks.',
    year: '2024',
    categories: ['Cloud Security'],
    tags: ['aws', 'gcp', 'cis', 'baseline', 'terraform'],
    links: [],
    featured: true,
    imageUrl: '/demo/sample.svg',
    contributors: ['A. Gupta', 'P. Subedi'],
  },
  {
    id: 'proj-redteam-ops-2023',
    title: 'Red Team Operational Toolkit (2023)',
    abstract: 'A curated collection of red-team tooling, automated operation playbooks, and C2 infrastructure templates used during internal assessments.',
    year: '2023',
    categories: ['Red Team'],
    tags: ['redteam', 'c2', 'cobalt-strike', 'powershell', 'ops'],
    links: [],
    featured: false,
    imageUrl: '/demo/malware.svg',
    contributors: ['C. Thapa', 'B. Gurung'],
  },
  {
    id: 'proj-blue-dashboard-2023',
    title: 'Blue Team SOC Dashboard (2023)',
    abstract: 'A real-time SOC dashboard aggregating logs and alerts from multiple sources for quick analyst triage and incident tracking.',
    year: '2023',
    categories: ['SIEM'],
    tags: ['dashboard', 'soc', 'elk', 'grafana', 'alerting'],
    links: [],
    featured: false,
    imageUrl: '/demo/pcap.svg',
    contributors: ['D. Rana', 'S. Khanal'],
  },
  {
    id: 'proj-ctf-automation-2024',
    title: 'CTF Challenge Automation & Scripting Kit (2024)',
    abstract: 'A toolkit of scripts, templates, and automation tools to speed up CTF challenge solving across forensics, web, crypto, and pwn categories.',
    year: '2024',
    categories: ['Research'],
    tags: ['ctf', 'automation', 'pwntools', 'python', 'scripting'],
    links: [
      { label: 'GitHub', url: 'https://github.com/example/ctf-kit', type: 'github' }
    ],
    featured: false,
    imageUrl: '/demo/sample.svg',
    contributors: ['Team CyberShield'],
  },
];
