import { Publication } from './types';

export const PUBLICATIONS: Publication[] = [
  {
    id: 'pub-2025-01',
    title: 'Adaptive Ransomware Family Classification using Temporal Graph Signals',
    kind: 'Paper',
    publicationDate: '2025-11-18',
    venue: 'IEEE International Conference on Communications and Network Security (CNS)',
    publisher: 'IEEE',
    abstract:
      'This work proposes a temporal graph signal representation of ransomware behavior traces and demonstrates robust family classification under obfuscation and packing variants.',
    keywords: ['Ransomware', 'Graph Signal Processing', 'Behavioral Analytics', 'Malware Detection'],
    authors: ['M. Pranav', 'A. Neelima', 'R. Vasanth'],
    link: 'https://doi.org/10.1109/example.2025.10001',
  },
  {
    id: 'pub-2025-02',
    title: 'A Lightweight Zero-Trust Policy Engine for Campus Edge Networks',
    kind: 'Paper',
    publicationDate: '2025-09-06',
    venue: 'Springer Journal of Network and Systems Management',
    publisher: 'Springer',
    abstract:
      'The paper introduces a low-overhead policy decision model for micro-segmentation in educational network environments with dynamic device trust scoring.',
    keywords: ['Zero Trust', 'Micro-segmentation', 'Policy Engine', 'Network Security'],
    authors: ['K. Sruthi', 'J. Harish', 'N. Darshan'],
    link: 'https://link.springer.com/article/example-2025-02',
  },
  {
    id: 'pub-2025-03',
    title: 'Secure Federated Learning for Intrusion Detection in Multi-Tenant Labs',
    kind: 'Paper',
    publicationDate: '2025-07-22',
    venue: 'Elsevier Computers & Security',
    publisher: 'Elsevier',
    abstract:
      'A privacy-preserving federated training strategy is developed for intrusion detection across isolated academic labs, reducing leakage while retaining detection performance.',
    keywords: ['Federated Learning', 'Intrusion Detection', 'Privacy', 'Cybersecurity'],
    authors: ['P. Hemanth', 'S. Aashika'],
    link: 'https://www.sciencedirect.com/science/article/pii/example2025',
  },
  {
    id: 'pub-2025-04',
    title: 'Context-Aware Phishing Defense System with Browser-Side Risk Scoring',
    kind: 'Patent',
    publicationDate: '2025-04-14',
    venue: 'Indian Patent Office',
    publisher: 'IP India',
    abstract:
      'This patent discloses a client-side phishing detection framework combining URL semantics, visual similarity, and interaction telemetry for dynamic risk scoring.',
    keywords: ['Phishing', 'Browser Security', 'Risk Scoring', 'Patent'],
    authors: ['R. Nivedita', 'A. Sai Kiran', 'V. Akash'],
    link: 'https://ipindia.gov.in/writereaddata/Portal/IPOJournal/example2025.pdf',
  },
  {
    id: 'pub-2025-05',
    title: 'Benchmarking SOC Alert Triage using Retrieval-Augmented Incident Context',
    kind: 'Paper',
    publicationDate: '2025-02-10',
    venue: 'ACM Asia Conference on Computer and Communications Security (ASIACCS)',
    publisher: 'ACM',
    abstract:
      'The study evaluates retrieval-augmented workflows for SOC triage and reports improvements in analyst response consistency over baseline playbook-only approaches.',
    keywords: ['SOC', 'Incident Response', 'RAG', 'Alert Triage'],
    authors: ['S. Yuvan', 'M. Harini'],
    link: 'https://dl.acm.org/doi/example/2025-05',
  },
  {
    id: 'pub-2024-01',
    title: 'Cross-Cloud Misconfiguration Detection via Policy Graph Canonicalization',
    kind: 'Paper',
    publicationDate: '2024-10-28',
    venue: 'IEEE Cloud Summit',
    publisher: 'IEEE',
    abstract:
      'This paper presents a canonical graph model that maps cloud IAM and resource policies into comparable structures to detect risky drift across providers.',
    keywords: ['Cloud Security', 'Misconfiguration', 'Policy Graph', 'IAM'],
    authors: ['T. Shreya', 'L. Dinesh', 'M. Niranjan'],
    link: 'https://doi.org/10.1109/example.2024.20001',
  },
  {
    id: 'pub-2024-02',
    title: 'Real-Time Malware Family Attribution from API Call Sequences',
    kind: 'Paper',
    publicationDate: '2024-08-16',
    venue: 'Springer Lecture Notes in Computer Science (LNCS)',
    publisher: 'Springer',
    abstract:
      'A sequence-aware attribution model is proposed for malware family recognition under runtime constraints suitable for endpoint monitoring agents.',
    keywords: ['Malware Analysis', 'API Sequences', 'Endpoint Security'],
    authors: ['A. Vetrivel', 'N. Divya'],
    link: 'https://link.springer.com/chapter/example-2024-02',
  },
  {
    id: 'pub-2024-03',
    title: 'Differential-Privacy Assisted Student Threat-Intel Sharing Framework',
    kind: 'Patent',
    publicationDate: '2024-06-09',
    venue: 'Indian Patent Office',
    publisher: 'IP India',
    abstract:
      'The patent defines a threat-intelligence sharing pipeline with differential privacy controls to preserve participant anonymity while retaining actionable indicators.',
    keywords: ['Threat Intelligence', 'Differential Privacy', 'Patent'],
    authors: ['S. Lekha', 'D. Arul', 'P. Akilan'],
    link: 'https://ipindia.gov.in/writereaddata/Portal/IPOJournal/example2024.pdf',
  },
  {
    id: 'pub-2024-04',
    title: 'Explainable Botnet Detection in IoT Traffic using Hybrid Attention Models',
    kind: 'Paper',
    publicationDate: '2024-03-02',
    venue: 'Elsevier Internet of Things Journal',
    publisher: 'Elsevier',
    abstract:
      'The article proposes a hybrid attention architecture with explainability maps to identify botnet behavior in constrained IoT telemetry streams.',
    keywords: ['IoT Security', 'Botnet Detection', 'Explainable AI'],
    authors: ['C. Hemalatha', 'R. Sharan'],
    link: 'https://www.sciencedirect.com/science/article/pii/example2024',
  },
  {
    id: 'pub-2023-01',
    title: 'Toward Practical Memory Forensics Pipelines for Undergraduate SOC Labs',
    kind: 'Paper',
    publicationDate: '2023-11-13',
    venue: 'IEEE Region 10 Conference (TENCON)',
    publisher: 'IEEE',
    abstract:
      'This conference paper details a repeatable memory forensics workflow that balances pedagogical simplicity with realistic triage fidelity.',
    keywords: ['Memory Forensics', 'SOC Labs', 'Incident Investigation'],
    authors: ['K. Aarthi', 'S. Monish'],
    link: 'https://doi.org/10.1109/example.2023.30001',
  },
  {
    id: 'pub-2023-02',
    title: 'A Comparative Study of Open-Source SIEM Pipelines for Academic Environments',
    kind: 'Paper',
    publicationDate: '2023-07-07',
    venue: 'Springer SN Computer Science',
    publisher: 'Springer',
    abstract:
      'The study compares open-source SIEM stacks on ingestion throughput, detection extensibility, and maintainability for student-driven operations.',
    keywords: ['SIEM', 'Log Analytics', 'Blue Team'],
    authors: ['V. Keshav', 'M. Keerthana', 'R. Ashwin'],
    link: 'https://link.springer.com/article/example-2023-02',
  },
  {
    id: 'pub-2023-03',
    title: 'Human-in-the-Loop Labeling for Security Alert Deduplication',
    kind: 'Poster',
    publicationDate: '2023-03-18',
    venue: 'ACM Student Research Competition',
    publisher: 'ACM',
    abstract:
      'A poster contribution showcasing an interactive annotation pipeline that improves duplicate alert suppression for SOC analysts.',
    keywords: ['Alert Deduplication', 'Human-in-the-Loop', 'SOC'],
    authors: ['N. Kavin', 'P. Janani'],
    link: 'https://dl.acm.org/doi/example/2023-03',
  },
];
